


### Get Request - FirebaseFunctions
GET https://student-qb-be-t4m7k7vxoa-uc.a.run.app
Content-Type: application/json


### Post Request - FirebaseFunctions
POST https://student-qb-be-t4m7k7vxoa-uc.a.run.app/file-uploaded
Content-Type: application/json

